id: AC8638991
title: The Root Verses on the Six Bardos
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:31:33.165791
  last_modified_at: 2022-03-01 03:31:33.165793
