id: AC8638991
title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:31:33.168997
  last_modified_at: 2022-03-01 03:31:33.169000
