id: AC8638991
title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren) for
  the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the Great Compassionate
  One from the Longchen Nyingtik'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:31:33.163296
  last_modified_at: 2022-03-01 03:31:33.163298
