id: AC8638991
title: Prayer for this Life, the Next and the Bardos
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:31:33.162175
  last_modified_at: 2022-03-01 03:31:33.162178
