id: AC8638991
title: 'Fostering Recollection to Dispel the Torment of Deluded Perception: An Aspiration
  for the Bardos'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:31:33.160610
  last_modified_at: 2022-03-01 03:31:33.160615
